kind: pipeline
type: docker
name: deploy

steps:
  - name: Build da Imagem Docker
    image: docker:latest
    commands:
      - docker build -t portal_licenciado:v0.0.1 .

  - name: Subir Serviço no Docker Swarm
    image: docker:latest
    commands:
      - docker service rm app_portal_licenciado || true
      - docker stack deploy -c Docker-compose.yml app
