version: "3.8"

services:
  portal_licenciado:
    image: portal_licenciado:v0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
      - traefik_public
        #ports:
        #- "3000:80"
        #- "3000:443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.portal_licenciado.rule=Host(`licenciado.akrbrands.com.br`)"
        - "traefik.http.routers.portal_licenciado.entrypoints=websecure"
        - "traefik.http.routers.portal_licenciado.priority=1"
        - "traefik.http.routers.portal_licenciado.tls.certresolver=le"
        - "traefik.http.routers.portal_licenciado.service=portal_licenciado"
        - "traefik.http.services.portal_licenciado.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true

