version: "3.8"

services:
  portal_licenciado:
    image: portal_licenciado:v0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    ports:
      - "3010:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
     

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true

